# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ccb3ea35aef1b787b73c0c9013ce7a6454bf06799fa0f30d87d7f8d0ae5aba1955b01caa0f2449b74ec7be480cbb61270ece8bba0937a625e23945638f29aba

test:
  secret_key_base: 07885c841ff35a7cacb89fa2233c12723b485c89e8e93a14b3de33112bbf5f81320b4ff791f5b48dc679ba05914b21f25f66f9ed46049aa8553cd6a280eeafdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
